name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call-simple-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      message: "Hello from the main workflow!"
