name: configuration variables
on:
  workflow_dispatch
env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      FirstName: John
      project_id: your-project-id-here  # Add the actual project ID or pass it as an input

    steps:
      - name: greeting step
        run: echo "$Greeting $FirstName is using $cloud with project ${{ env.project_id }}"
