name: Node.js CI with ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: List files in 'frontend' directory (for debugging purposes)
      - name: List files in frontend
        run: |
          cd frontend  # Change to 'frontend' directory
          ls -R        # List files recursively in the directory

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          cd frontend  # Change to 'frontend' directory
          npm install

      # Step 5: Enforce Code Style (ESLint)
      - name: Enforce Code Style (ESLint)
        run: |
          cd frontend  # Change to 'frontend' directory
          npx eslint . --ext .js,.jsx,.ts,.tsx --fix  # Lint JavaScript/TypeScript files
        continue-on-error: false

      # Step 6: Run tests
      - name: Run tests
        run: |
          cd frontend  # Change to 'frontend' directory
          npm test
