name: Simple Job Dependency Workflow (No npm)

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          echo "Building project..."
          # Simulate building by creating a file or running any other build steps
          mkdir build
          echo "This is a build file" > build/output.txt
          cat build/output.txt  # Output the build result

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the successful completion of the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy project
        run: |
          echo "Deploying project..."
          # Simulate deployment (you can replace this with actual deployment commands)
          if [ -f build/output.txt ]; then
            echo "Deployment successful! The build file is available."
          else
            echo "Deployment failed! No build file found."
          fi
