name: Add Numbers Workflow

on:
  workflow_call:
    inputs:
      number1:
        description: 'First number'
        required: true
        type: number
      number2:
        description: 'Second number'
        required: true
        type: number

    outputs:
      sum:
        description: 'Sum of the two numbers'
        value: ${{ jobs.add-numbers.outputs.sum }}

jobs:
  add-numbers:
    name: Add two numbers
    runs-on: ubuntu-latest

    outputs:
      sum: ${{ steps.calculate.outputs.sum }}

    steps:
      - name: Calculate sum
        id: calculate
        run: |
          echo "Inputs received: number1=${{ inputs.number1 }}, number2=${{ inputs.number2 }}"
          sum=$(( ${{ inputs.number1 }} + ${{ inputs.number2 }} ))
          echo "Sum is: $sum"
          echo "sum=$sum" >> $GITHUB_OUTPUT
