name: secrests
on:
  workflow_dispatch
env:
  ACTIONS_STEP_DEBUG: true
  jobs:
    test_secrets:
      runs-on: ubuntu-latest
      steps:
        - name: "Secrets Step"
          run: |
            echo "My Secret is ${{ secrets.MY_KEY }}"