name: Build spring boot application with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Build with Maven
        working-directory: ./springboot/test
        run: mvn clean install

      - name: Run tests with Maven
        working-directory: ./springboot/test
        run: mvn test
