name: Build Spring Boot Application with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Cache Maven repository
        uses: actions/cache@v3
        with: 
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get Git commit version
        id: version
        run: |
          echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Build with Maven
        working-directory: ./springboot/test
        run: mvn clean install -Dgit.commit=${{ env.GIT_COMMIT }} -Dgit.tag=${{ env.GIT_TAG }}

      - name: Run tests with Maven
        working-directory: ./springboot/test
        run: mvn test -Dgit.commit=${{ env.GIT_COMMIT }} -Dgit.tag=${{ env.GIT_TAG }}
