name: Build Spring Boot Application with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Cache Maven repository
        uses: actions/cache@v3
        with: 
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get Git commit version
        id: version
        run: |
          echo "GITHUB_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GITHUB_RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
          echo "VERSION=test-0.0.${{ github.run_number }}-${{ github.sha }}-SNAPSHOT" >> $GITHUB_ENV

      - name: Build with Maven
        working-directory: ./springboot/test
        run: mvn clean install -Dversion=${{ env.VERSION }}

      - name: Run tests with Maven
        working-directory: ./springboot/test
        run: mvn test -Dversion=${{ env.VERSION }}
