name: "Terraform"

on:
  push:
    branches: ["master"]
  pull_request:

permissions:
  contents: write
  actions: write
  checks: write
  deployments: write
  id-token: write
  repository-projects: write

jobs:
  # ✅ Reusable workflow job (make sure the called workflow accepts it)
  call-workflow-passing-data:
    uses: brianacharya001/GHA/.github/workflows/automate-readme.yml@master

  # ✅ Terraform Job
  terraform:
    name: "Terraform"
    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        # Uncomment if using Terraform Cloud
        # with:
        #   cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
