name: "Terraform Local VM HTTPD Install"

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  terraform:
    name: "Install HTTPD on Local VM"
    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
